"""empty message

Revision ID: 828acdc4969e
Revises: 3f14c9af10c9
Create Date: 2020-04-10 22:10:12.469390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828acdc4969e'
down_revision = '3f14c9af10c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
